name: Windows-Linux-CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows (static)
            os: windows-latest
            shared: OFF
          - name: Windows (shared)
            os: windows-latest
            shared: ON
          - name: Linux (static)
            os: ubuntu-latest
            shared: OFF
          - name: Linux (shared)
            os: ubuntu-latest
            shared: ON
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: "**/vcpkg.json"
        vcpkgDirectory: "${{ github.workspace }}/vcpkg"
        vcpkgGitCommitId: "62159a45e18f3a9ac0548628dcaf74fcb60c6ff9"
    - name: Install simdjson
      run: |
        $VCPKG_ROOT/vcpkg install simdjson
      shell: bash
    - name: Configure
      run:  cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=${{ matrix.shared }} -B build
    - name: Build 
      run: cmake --build build --verbose
